### ISSUE TITLE
bug: background and styling inconsistency in embedded p2pad's iframe Preview

### ISSUE THREAD

**Issue by akhileshthite** [AgregoreWeb/website#65] opened 2024-11-07 09:14 UTC
The `iframe` preview in the p2pad's embedded code editor does not consistently apply the background color and font styling defined in the base CSS. When user-defined HTML, CSS, or JavaScript is added, it can override or conflict with the base styles, resulting in an unpredictable appearance. Attempts to enforce base styles using `#content-wrapper` or `!important` directives have not fully resolved the issue. 

This inconsistency affects the visual layout and readability of the previewed content:
![Screenshot 2024-11-07 at 1 08 12 AM](https://github.com/user-attachments/assets/b368c872-bc35-4323-b7d0-5d59fcc2acfb)

https://github.com/AgregoreWeb/website/tree/main/docs/examples/p2pad

**Comment by akhileshthite** [comment] 2024-11-07 09:15
@tripledoublev

**Comment by RangerMauve** [comment] 2024-11-13 15:31
I think the issue is p2pad is trying to enforce the Agregore themes by default. It looks like the style being applied is setting the background on [*all* elements](https://github.com/AgregoreWeb/website/blob/main/docs/examples/p2pad/codeEditor.js#L11). Might be worth it to test having it import `@import url("agregore://theme/style.css")`

**Comment by tripledoublev** [comment] 2024-11-13 16:27
@RangerMauve, you are right that the error was coming from the * universal selector
#66 
- Removed *
- Imports theme/style.css

**Comment by RangerMauve** [comment] 2024-11-13 18:15
Merged. TY!

**Closed** 2024-11-15 00:02 UTC
